/**
 * PDF Export Engine
 *
 * Converts report HTML to PDF using browser print API
 * with proper styling and live data binding.
 */

export interface PDFExportOptions {
 title: string;
 author?: string;
 orientation?: 'portrait' | 'landscape';
 includeHeader?: boolean;
 includeFooter?: boolean;
}

/**
 * Exports report content to PDF
 */
export async function exportReportToPDF(
 htmlContent: string,
 options: PDFExportOptions
): Promise<void> {
 const {
 title = 'Audit Report',
 author = 'Sentinel GRC',
 orientation = 'portrait',
 includeHeader = true,
 includeFooter = true,
 } = options;

 const printWindow = window.open('', '_blank', 'width=800,height=600');

 if (!printWindow) {
 throw new Error('Failed to open print window. Please allow popups for this site.');
 }

 const timestamp = new Date().toLocaleString();

 const pdfHtml = `
<!DOCTYPE html>
<html>
<head>
 <meta charset="UTF-8">
 <title>${title}</title>
 <style>
 @page {
 size: ${orientation};
 margin: 2cm;
 }

 * {
 box-sizing: border-box;
 }

 body {
 font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
 font-size: 11pt;
 line-height: 1.6;
 color: #1e293b;
 background: white;
 margin: 0;
 padding: 20px;
 }

 h1 {
 font-size: 24pt;
 font-weight: bold;
 color: #0f172a;
 margin: 0 0 20px 0;
 border-bottom: 3px solid #3b82f6;
 padding-bottom: 10px;
 }

 h2 {
 font-size: 18pt;
 font-weight: bold;
 color: #1e293b;
 margin: 30px 0 15px 0;
 }

 h3 {
 font-size: 14pt;
 font-weight: bold;
 color: #334155;
 margin: 20px 0 10px 0;
 }

 p {
 margin: 0 0 12px 0;
 text-align: justify;
 }

 ul, ol {
 margin: 10px 0;
 padding-left: 30px;
 }

 li {
 margin: 5px 0;
 }

 table {
 width: 100%;
 border-collapse: collapse;
 margin: 20px 0;
 font-size: 10pt;
 }

 th {
 background-color: #f1f5f9;
 padding: 8px;
 text-align: left;
 font-weight: bold;
 border: 1px solid #cbd5e1;
 }

 td {
 padding: 6px 8px;
 border: 1px solid #e2e8f0;
 }

 tr:nth-child(even) {
 background-color: #f8fafc;
 }

 .header {
 text-align: center;
 margin-bottom: 30px;
 padding-bottom: 15px;
 border-bottom: 2px solid #cbd5e1;
 }

 .header h1 {
 border: none;
 margin: 0;
 }

 .header .subtitle {
 color: #64748b;
 font-size: 10pt;
 margin-top: 5px;
 }

 .footer {
 margin-top: 50px;
 padding-top: 15px;
 border-top: 1px solid #cbd5e1;
 font-size: 9pt;
 color: #64748b;
 text-align: center;
 }

 .page-break {
 page-break-after: always;
 }

 .severity-badge {
 display: inline-block;
 padding: 2px 8px;
 border-radius: 4px;
 font-size: 9pt;
 font-weight: bold;
 }

 .severity-critical {
 background-color: #fee2e2;
 color: #991b1b;
 }

 .severity-high {
 background-color: #ffedd5;
 color: #c2410c;
 }

 .severity-medium {
 background-color: #fef3c7;
 color: #92400e;
 }

 .severity-low {
 background-color: #dbeafe;
 color: #1e40af;
 }

 .status-open {
 background-color: #fef3c7;
 color: #92400e;
 }

 .status-closed {
 background-color: #d1fae5;
 color: #065f46;
 }

 svg {
 max-width: 100%;
 height: auto;
 display: block;
 margin: 20px auto;
 }

 .block-container {
 margin: 25px 0;
 page-break-inside: avoid;
 }

 .block-header {
 background: linear-gradient(to right, #1e293b, #334155);
 color: white;
 padding: 10px 15px;
 font-weight: bold;
 font-size: 11pt;
 margin-bottom: 10px;
 }

 .block-content {
 border: 1px solid #e2e8f0;
 padding: 15px;
 background: white;
 }

 .stats-grid {
 display: grid;
 grid-template-columns: repeat(3, 1fr);
 gap: 15px;
 margin: 15px 0;
 }

 .stat-card {
 text-align: center;
 padding: 10px;
 background: #f8fafc;
 border: 1px solid #e2e8f0;
 border-radius: 4px;
 }

 .stat-label {
 font-size: 9pt;
 color: #64748b;
 margin-bottom: 5px;
 }

 .stat-value {
 font-size: 18pt;
 font-weight: bold;
 color: #0f172a;
 }

 .ai-notice {
 background: #dbeafe;
 border-left: 4px solid #3b82f6;
 padding: 10px 15px;
 margin: 15px 0;
 font-size: 9pt;
 color: #1e40af;
 }

 @media print {
 body {
 padding: 0;
 }

 .no-print {
 display: none;
 }
 }
 </style>
</head>
<body>
 ${
 includeHeader
 ? `
 <div class="header">
 <h1>${title}</h1>
 <div class="subtitle">Generated by ${author} | ${timestamp}</div>
 </div>
 `
 : ''
 }

 <div class="content">
 ${htmlContent}
 </div>

 ${
 includeFooter
 ? `
 <div class="footer">
 <div>This report was generated by Sentinel GRC v3.0 on ${timestamp}</div>
 <div style="margin-top: 5px;">
 Confidential - For authorized personnel only
 </div>
 </div>
 `
 : ''
 }

 <script>
 // Auto-trigger print dialog after content loads
 window.onload = function() {
 setTimeout(() => {
 window.print();
 // Close window after print dialog is dismissed
 window.onafterprint = function() {
 window.close();
 };
 }, 500);
 };
 </script>
</body>
</html>
 `;

 printWindow.document.write(pdfHtml);
 printWindow.document.close();
}

/**
 * Downloads content as HTML file (fallback if PDF generation fails)
 */
export function downloadAsHTML(htmlContent: string, filename: string): void {
 const blob = new Blob([htmlContent], { type: 'text/html' });
 const url = URL.createObjectURL(blob);
 const link = document.createElement('a');
 link.href = url;
 link.download = `${filename}.html`;
 document.body.appendChild(link);
 link.click();
 document.body.removeChild(link);
 URL.revokeObjectURL(url);
}

/**
 * Prepares HTML content for PDF export by:
 * - Resolving block markers
 * - Ensuring proper styling
 * - Adding page breaks
 */
export function prepareContentForPDF(htmlContent: string): string {
 let prepared = htmlContent;

 prepared = prepared.replace(
 /{{RiskHeatmap}}/g,
 '<div class="block-container"><div class="block-header">📊 Strategic Risk Heatmap</div><div class="block-content"><p><em>[Live Risk Heatmap visualization embedded in PDF export]</em></p></div></div>'
 );

 prepared = prepared.replace(
 /{{FindingTable}}/g,
 '<div class="block-container"><div class="block-header">📋 Open Findings Table</div><div class="block-content"><p><em>[Dynamic findings table embedded in PDF export]</em></p></div></div>'
 );

 prepared = prepared.replace(
 /{{ExecutiveSummary}}/g,
 '<div class="block-container"><div class="block-header">🤖 Executive Summary (AI Generated)</div><div class="block-content"><p><em>[AI-generated executive summary embedded in PDF export]</em></p><div class="ai-notice">This summary was generated by Sentinel Prime AI based on live system data.</div></div></div>'
 );

 return prepared;
}
